// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2z48vp8KrWnIusHeGE7kNpWCrUYUlPBA',
    appId: '1:373259438517:web:ce8fecfe8a5dffe76a71fc',
    messagingSenderId: '373259438517',
    projectId: 'boy-barbershop',
    authDomain: 'boy-barbershop.firebaseapp.com',
    storageBucket: 'boy-barbershop.firebasestorage.app',
    measurementId: 'G-QZGKY74MBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpoZQJEWuinLiIlq-nfo7qzzCQveMhyds',
    appId: '1:373259438517:android:ed6a30f7ecf9645f6a71fc',
    messagingSenderId: '373259438517',
    projectId: 'boy-barbershop',
    storageBucket: 'boy-barbershop.firebasestorage.app',
  );
}
